version: "3.7"
services:
  instagram-db:
    image: postgres:latest
    restart: always
    container_name: instagram-db
    platform: linux/arm64
    env_file:
      - docker-compose-local.env
    ports:
      - '5432:5432'
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - instagram-volume:/var/lib/postgresql/data/
    networks:
      - instagram-network

networks:
  instagram-network:

volumes:
  instagram-volume:
